[project]
project_id = "byjyyshxviieqkymavnh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 5432
host = "aws-0-eu-central-1.pooler.supabase.com"
user = "postgres.byjyyshxviieqkymavnh"
password = "Sa2507!Dma2307"
database = "postgres"

[studio]
enabled = true
port = 54323
api_url = "https://byjyyshxviieqkymavnh.supabase.co" 